//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsMeasurement
    {
        public int id_measure { get; set; }
        public string name_unit { get; set; }
    }
}
