//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarisation.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WriteOff
    {
        public int id { get; set; }
        public int id_inventory { get; set; }
        public Nullable<int> count_writeoff { get; set; }
        public string reason { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
